### ISSUE TITLE
Where is the straight forward, direct link to all the keyboard shortcuts of this extension?

### ISSUE THREAD

**Issue by fmorriso** [rebornix/vscode-vs-keybindings#26]
"You can see all the keyboard shortcuts in the extension's contribution list."

What does this mean?  I cannot find it.

Please provide a straight-forward, easy-to-find, direct link on the main page of this extension to a list (such as markdown or pdf)  of the replacement keyboard shortcuts this extension supplies.

**Comment by cpmcgrath** [comment]
If you go to the Extension list in Visual Studio Code, find Visual Studio Keymap (Doesn't need to be installed), it brings up details of the Extension. Up the top, it shows 4 sections: Details, Contributions, Changelog, Dependencies. If you choose Contributions it shows all the commands and what they map to.

**Comment by fmorriso** [comment]
Looking in **Contributions** instead of something like **Documentation** or **Keyboard Shortcuts** is not __straight forward__.     You cannot play this type of peek-a-boo with the documentation of how to use an extension and expect wide-spread adoption.

**Comment by cpmcgrath** [comment]
I agree that it's more hidden than ideal, however, that's the standard documentation location for this in Visual Studio Code.
With that in mind, I think if you believe it's too hidden I'd suggest raising it with the Visual Studio Code team.

By using it as the shortcut documentation, it means the extension only has to maintain a single list of changes instead of two. I agree with the Author's decision to use it.

**Comment by rebornix** [comment]
This issue was moved to Microsoft/vscode-vs-keybindings#3
